-- USE [CarRecoveryDB];
-- GO

IF OBJECT_ID('dbo.CarRecoveries', 'U') IS NOT NULL
    DROP TABLE dbo.CarRecoveries;
GO

CREATE TABLE dbo.CarRecoveries (
    NumberPlate VARCHAR(15) NOT NULL PRIMARY KEY,

    CarModel VARCHAR(50) NOT NULL,

    Issue TEXT,
    Location VARCHAR(255) NOT NULL,

    BreakdownTime DATETIME DEFAULT GETDATE(),

    Status VARCHAR(20) DEFAULT 'Pending'
);

GO

INSERT INTO dbo.CarRecoveries (NumberPlate, CarModel, Issue, Location, BreakdownTime, Status) VALUES
('UT27 BAA', 'Mercedes E-Class', 'Tyre blowout at speed', 'A66 near Penrith', GETDATE(), 'Pending'),
('TC19 HHH', 'Vauxhall Insignia', 'Water pump failure', 'M4 Junction 7, Slough', GETDATE(), 'In Progress'),
('BL37 BKK', 'BMW 1 Series', 'Cracked windscreen - unsafe', 'M6 Junction 40, Penrith', GETDATE(), 'Pending'),
('GG86 FBB', 'Fiat 500', 'Alternator failure', 'A34 near Oxford', GETDATE(), 'In Progress'),
('JD56 ANN', 'Mercedes C-Class', 'CV joint clicking - broken', 'Sainsbury''s, Exeter', GETDATE(), 'Pending'),
('LC80 CHH', 'Toyota Aygo', 'Jump start needed', 'M4 Junction 37, Bridgend', GETDATE(), 'Pending'),
('VB44 OOO', 'Kia Sorento', 'Suspension arm broken', 'A38 near Plymouth', GETDATE(), 'In Progress'),
('UL48 NNN', 'Audi A4', 'Bonnet latch broken', 'Asda car park, Leeds', DATEADD(DAY, -1, GETDATE()), 'Pending'),
('TF38 EHH', 'Ford Kuga', 'Battery dead', 'A46 near Newark', DATEADD(DAY, -1, GETDATE()), 'Pending'),
('FX25 RRR', 'Audi Q5', 'Clutch slipping', 'A1(M) Junction 40, Wakefield', DATEADD(DAY, -1, GETDATE()), 'Pending'),
('UU24 DKK', 'Fiat 500', 'Gearbox oil leak', 'M4 Junction 7, Slough', DATEADD(DAY, -1, GETDATE()), 'Completed'),
('DJ40 ATT', 'Honda Jazz', 'Tyre blowout at speed', 'M40 Junction 10, Banbury', DATEADD(DAY, -1, GETDATE()), 'Pending'),
('LY81 KKK', 'Vauxhall Mokka', 'Battery dead', 'A38 near Plymouth', DATEADD(DAY, -2, GETDATE()), 'Pending'),
('OF46 JJJ', 'Mazda CX-5', 'Alternator belt snapped', 'A14 Junction 45, Newmarket', DATEADD(DAY, -2, GETDATE()), 'Pending'),
('BR28 GFF', 'Citroen Berlingo', 'Fuel pump failure', 'M20 Junction 8, Maidstone', DATEADD(DAY, -2, GETDATE()), 'In Progress'),
('FH22 EJJ', 'Seat Ateca', 'Charging port fault', 'M1 Junction 15A, Northampton', DATEADD(DAY, -2, GETDATE()), 'In Progress'),
('AY39 AMM', 'Toyota Prius', 'Turbo failure - loss of power', 'A1 near Grantham', DATEADD(DAY, -2, GETDATE()), 'Pending'),
('PD63 BGG', 'Nissan Leaf', 'Water pump failure', 'A34 near Oxford', DATEADD(DAY, -2, GETDATE()), 'In Progress'),
('KK47 GFF', 'Honda CR-V', 'Bonnet latch broken', 'Tesco car park, Bristol', DATEADD(DAY, -2, GETDATE()), 'In Progress'),
('YD20 MMM', 'Audi A3', 'Gearbox stuck in second', 'M6 Junction 9, Wednesbury', DATEADD(DAY, -2, GETDATE()), 'Completed'),
('YW35 EEE', 'Vauxhall Astra', 'Charging port fault', 'M6 Junction 21A, Warrington', DATEADD(DAY, -2, GETDATE()), 'Pending'),
('VB73 LLL', 'Seat Ateca', 'Brake fluid low', 'M62 Junction 8, Warrington', DATEADD(DAY, -2, GETDATE()), 'Pending'),
('DJ92 AFF', 'Vauxhall Astra', 'Won''t start', 'M4 Junction 47, Swansea', DATEADD(DAY, -2, GETDATE()), 'Pending'),
('GE66 EGG', 'Toyota Aygo', 'Fuel leak - smell of petrol', 'Asda car park, Leeds', DATEADD(DAY, -2, GETDATE()), 'In Progress'),
('SV46 EHH', 'Audi A3', 'Flat tyre', 'A303 near Amesbury', DATEADD(DAY, -2, GETDATE()), 'Pending'),
('MS58 CAA', 'Volvo V40', 'Gearbox oil leak', 'A1 near Newark', DATEADD(DAY, -2, GETDATE()), 'In Progress'),
('OV32 GGG', 'Honda HR-V', 'Clutch slipping', 'M20 Junction 8, Maidstone', DATEADD(DAY, -2, GETDATE()), 'Pending'),
('JR23 GFF', 'Ford Kuga', 'Bonnet latch broken', 'B&Q car park, Reading', DATEADD(DAY, -2, GETDATE()), 'Pending'),
('RP78 DBB', 'Peugeot 308', 'Oil pressure warning', 'M4 Junction 7, Slough', DATEADD(DAY, -3, GETDATE()), 'In Progress'),
('DP15 EAA', 'Mazda CX-5', 'Immobiliser fault', 'M4 Junction 7, Slough', DATEADD(DAY, -3, GETDATE()), 'Completed'),
('RW63 GBB', 'BMW X5', 'Gearbox fault', 'M6 Junction 12, Cannock', DATEADD(DAY, -3, GETDATE()), 'Pending'),
('GE12 CHH', 'Toyota Yaris', 'Fuel leak - smell of petrol', 'M4 Junction 32, Cardiff', DATEADD(DAY, -4, GETDATE()), 'In Progress'),
('NF71 BDD', 'BMW 1 Series', 'Brake pads worn through', 'A14 near Huntingdon', DATEADD(DAY, -4, GETDATE()), 'Pending'),
('JB68 FJJ', 'Mercedes E-Class', 'Gearbox stuck in second', 'A303 near Amesbury', DATEADD(DAY, -4, GETDATE()), 'In Progress'),
('CC12 GEE', 'Seat Ateca', 'Fuel leak - smell of petrol', 'M4 Junction 37, Bridgend', DATEADD(DAY, -4, GETDATE()), 'Completed'),
('XK39 FGG', 'Suzuki Swift', 'Clutch burnt out', 'A14 Junction 45, Newmarket', DATEADD(DAY, -4, GETDATE()), 'Pending'),
('RU74 CLL', 'Renault Clio', 'Gearbox stuck in second', 'High Street, Barnet', DATEADD(DAY, -4, GETDATE()), 'In Progress'),
('AO95 DAA', 'BMW 5 Series', 'DPF clogged - engine loss', 'M25 Junction 25, Enfield', DATEADD(DAY, -5, GETDATE()), 'In Progress'),
('VO62 CFF', 'BMW 1 Series', 'Brake pads worn through', 'A40 near Witney', DATEADD(DAY, -5, GETDATE()), 'Pending'),
('PA59 DKK', 'Renault Clio', 'Clutch burnt out', 'Sainsbury''s, Exeter', DATEADD(DAY, -5, GETDATE()), 'In Progress'),
('WL73 CKK', 'Audi TT', 'Alternator belt snapped', 'B&Q car park, Reading', DATEADD(DAY, -5, GETDATE()), 'Pending'),
('NL75 NNN', 'Toyota Prius', 'Coolant leak', 'M1 Junction 19, Lutterworth', DATEADD(DAY, -5, GETDATE()), 'In Progress'),
('VU44 AQQ', 'Renault Clio', 'DPF clogged - engine loss', 'A38 near Lichfield', DATEADD(DAY, -5, GETDATE()), 'Pending'),
('RG44 PPP', 'Honda Jazz', 'Brake fluid low', 'A1 near Peterborough', DATEADD(DAY, -5, GETDATE()), 'In Progress'),
('FD28 GBB', 'Fiat 500', 'Air bag warning light', 'A406 North Circular, London', DATEADD(DAY, -5, GETDATE()), 'Pending'),
('BB78 APP', 'Skoda Octavia', 'DPF clogged - engine loss', 'M25 Junction 25, Enfield', DATEADD(DAY, -5, GETDATE()), 'In Progress'),
('CP35 EDD', 'Honda Civic', 'Power steering loss', 'Retail park, Birmingham', DATEADD(DAY, -5, GETDATE()), 'In Progress'),
('CV71 KKK', 'Ford Focus', 'Turbo boost pipe split', 'M3 Junction 4, Fleet', DATEADD(DAY, -5, GETDATE()), 'Pending'),
('LH32 AGG', 'Seat Ibiza', 'Battery dead', 'Service station, M6', DATEADD(DAY, -5, GETDATE()), 'Completed'),
('TR53 DFF', 'Nissan Micra', 'Battery dead', 'A66 near Darlington', DATEADD(DAY, -5, GETDATE()), 'Pending');
 
INSERT INTO dbo.CarRecoveries (NumberPlate, CarModel, Issue, Location, BreakdownTime, Status) VALUES
('OM25 LLL', 'Citroen C3', 'Won''t come out of park', 'M25 Junction 12, Reigate', DATEADD(DAY, -5, GETDATE()), 'Pending'),
('JM15 BDD', 'Mercedes A-Class', 'Won''t start', 'M25 Junction 12, Reigate', DATEADD(DAY, -6, GETDATE()), 'Pending'),
('AY59 GFF', 'Seat Leon', 'Hybrid battery warning', 'A303 near Amesbury', DATEADD(DAY, -6, GETDATE()), 'Pending'),
('XD11 EAA', 'Volkswagen Polo', 'Suspension damage - pothole', 'Asda car park, Leeds', DATEADD(DAY, -6, GETDATE()), 'Pending'),
('JL73 ARR', 'Mercedes C-Class', 'Jump start needed', 'M1 Junction 24, East Midlands', DATEADD(DAY, -6, GETDATE()), 'Pending'),
('OJ31 AQQ', 'Citroen C3', 'Brake fluid low', 'A34 near Newbury', DATEADD(DAY, -6, GETDATE()), 'Pending'),
('OL69 DHH', 'Volvo V40', 'Fuel pump failure', 'Town centre, Coventry', DATEADD(DAY, -7, GETDATE()), 'In Progress'),
('VA34 BGG', 'Toyota Aygo', 'Oil leak - major', 'M25 Junction 30, Thurrock', DATEADD(DAY, -7, GETDATE()), 'In Progress'),
('MF57 TTT', 'Vauxhall Mokka', 'Hybrid battery warning', 'M25 Junction 30, Thurrock', DATEADD(DAY, -7, GETDATE()), 'Completed'),
('VY22 BHH', 'Audi Q7', 'Starter motor failed', 'A2 near Canterbury', DATEADD(DAY, -7, GETDATE()), 'Completed'),
('RL66 FAA', 'Skoda Kamiq', 'Flat tyre', 'A1 near Peterborough', DATEADD(DAY, -8, GETDATE()), 'Pending'),
('CY97 AFF', 'Seat Ateca', 'Electric power steering fault', 'A1(M) near Doncaster', DATEADD(DAY, -8, GETDATE()), 'In Progress'),
('TY87 FCC', 'Ford Focus', 'Fuel leak - smell of petrol', 'M25 Junction 12, Reigate', DATEADD(DAY, -8, GETDATE()), 'In Progress'),
('NL80 GKK', 'BMW 3 Series', 'Brake fluid low', 'Retail park, Birmingham', DATEADD(DAY, -9, GETDATE()), 'Pending'),
('UU23 ADD', 'BMW X3', 'Traction control fault', 'M3 Junction 3, Bagshot', DATEADD(DAY, -9, GETDATE()), 'Completed'),
('PT94 HHH', 'Nissan Leaf', 'CV joint clicking - broken', 'M11 Junction 7, Harlow', DATEADD(DAY, -9, GETDATE()), 'Pending'),
('GA21 CLL', 'Vauxhall Corsa', 'Two tyres flat', 'A1 near Grantham', DATEADD(DAY, -9, GETDATE()), 'In Progress'),
('YU32 CEE', 'Kia Sorento', 'Won''t come out of park', 'M25 Junction 12, Reigate', DATEADD(DAY, -9, GETDATE()), 'In Progress'),
('FS86 BCC', 'Vauxhall Insignia', 'Key fob not working - locked out', 'A30 near Bodmin', DATEADD(DAY, -9, GETDATE()), 'In Progress'),
('CJ33 GAA', 'Honda HR-V', 'Charging port fault', 'M3 Junction 4, Fleet', DATEADD(DAY, -9, GETDATE()), 'Completed'),
('BL54 BLL', 'Vauxhall Astra', 'Power steering loss', 'A316 near Twickenham', DATEADD(DAY, -9, GETDATE()), 'In Progress'),
('WY42 BEE', 'Ford Galaxy', 'Engine overheating', 'A50 near Stoke-on-Trent', DATEADD(DAY, -9, GETDATE()), 'Pending'),
('VB88 AFF', 'Peugeot 208', 'Brake disc cracked', 'A406 North Circular, London', DATEADD(DAY, -9, GETDATE()), 'In Progress'),
('MG25 EJJ', 'Renault Kadjar', 'Power steering loss', 'Asda car park, Leeds', DATEADD(DAY, -9, GETDATE()), 'Pending'),
('UA72 DAA', 'Seat Tarraco', 'Ran out of fuel', 'A34 near Newbury', DATEADD(DAY, -9, GETDATE()), 'Pending'),
('NC80 ADD', 'Toyota RAV4', 'Clutch slipping', 'M3 Junction 4, Fleet', DATEADD(DAY, -9, GETDATE()), 'Pending'),
('BM49 DDD', 'Skoda Superb', 'Power steering loss', 'M4 Junction 37, Bridgend', DATEADD(DAY, -9, GETDATE()), 'In Progress'),
('KF70 BAA', 'Seat Tarraco', 'Suspension arm broken', 'Sainsbury''s, Exeter', DATEADD(DAY, -9, GETDATE()), 'Pending'),
('OB95 HHH', 'BMW 5 Series', 'Turbo failure - loss of power', 'A3 near Hindhead', DATEADD(DAY, -9, GETDATE()), 'In Progress'),
('VM37 BAA', 'Hyundai Tucson', 'Engine warning light', 'A1(M) near Doncaster', DATEADD(DAY, -9, GETDATE()), 'Pending'),
('KC20 DAA', 'BMW X3', 'Engine overheating', 'A1(M) near Doncaster', DATEADD(DAY, -10, GETDATE()), 'In Progress'),
('KO14 EKK', 'Renault Megane', 'Oil leak - major', 'M6 Toll near Cannock', DATEADD(DAY, -10, GETDATE()), 'In Progress'),
('RB56 BDD', 'Citroen C5 Aircross', 'Fuel leak - smell of petrol', 'M3 Junction 3, Bagshot', DATEADD(DAY, -10, GETDATE()), 'Completed'),
('TF94 GHH', 'Audi TT', 'Oil leak - major', 'M62 Junction 8, Warrington', DATEADD(DAY, -11, GETDATE()), 'Completed'),
('PJ82 EEE', 'Volvo V40', 'Fuel leak - smell of petrol', 'M25 Junction 5, Sevenoaks', DATEADD(DAY, -11, GETDATE()), 'In Progress'),
('HX31 GBB', 'Volkswagen Golf', 'Alternator seized', 'A34 near Newbury', DATEADD(DAY, -11, GETDATE()), 'Completed'),
('WV65 EFF', 'Peugeot 3008', 'Wheel bearing noise', 'M40 Junction 1, Hillingdon', DATEADD(DAY, -11, GETDATE()), 'Pending'),
('NX73 DFF', 'Volkswagen Passat', 'Starter motor failed', 'High Street, Barnet', DATEADD(DAY, -12, GETDATE()), 'Pending'),
('TL14 ADD', 'Volkswagen Golf', 'Air bag warning light', 'A3 near Guildford', DATEADD(DAY, -12, GETDATE()), 'In Progress'),
('FN78 CJJ', 'BMW 3 Series', 'Won''t come out of park', 'Tesco Extra, Leicester', DATEADD(DAY, -12, GETDATE()), 'In Progress'),
('KA77 CGG', 'Renault Captur', 'Suspension damage - pothole', 'M1 Junction 10, Luton', DATEADD(DAY, -12, GETDATE()), 'Pending'),
('TV39 EGG', 'Audi A4', 'Bonnet latch broken', 'High Street, Barnet', DATEADD(DAY, -12, GETDATE()), 'Completed'),
('SK84 ACC', 'Vauxhall Insignia', 'Starter solenoid fault', 'M62 Junction 22, Rishworth', DATEADD(DAY, -12, GETDATE()), 'Pending'),
('SX50 ANN', 'Honda CR-V', 'Battery flat - lights left on', 'M25 Junction 5, Sevenoaks', DATEADD(DAY, -13, GETDATE()), 'In Progress'),
('SO84 BAA', 'Nissan Qashqai', 'Wheel bearing noise', 'M1 Junction 10, Luton', DATEADD(DAY, -13, GETDATE()), 'Completed'),
('EC68 DCC', 'Toyota Yaris', 'Tyre blowout at speed', 'M1 Junction 36, Barnsley', DATEADD(DAY, -13, GETDATE()), 'Pending'),
('AC41 DDD', 'Mercedes A-Class', 'Power steering loss', 'A40 near Witney', DATEADD(DAY, -13, GETDATE()), 'Completed'),
('YE54 GFF', 'Ford Focus', 'Radiator hose burst', 'M40 Junction 1, Hillingdon', DATEADD(DAY, -14, GETDATE()), 'Pending'),
('SF38 GGG', 'Seat Ateca', 'Flat tyre', 'A46 near Newark', DATEADD(DAY, -14, GETDATE()), 'In Progress'),
('BY50 OOO', 'Ford Focus', 'Battery flat - lights left on', 'Tesco Extra, Leicester', DATEADD(DAY, -14, GETDATE()), 'Completed');
 
INSERT INTO dbo.CarRecoveries (NumberPlate, CarModel, Issue, Location, BreakdownTime, Status) VALUES
('MW96 BAA', 'Hyundai i30', 'Flat tyre', 'M40 Junction 10, Banbury', DATEADD(DAY, -14, GETDATE()), 'Completed'),
('PE24 FAA', 'Nissan Qashqai', 'Water pump failure', 'M25 Junction 17, Chorleywood', DATEADD(DAY, -14, GETDATE()), 'Pending'),
('VS64 DDD', 'Kia Sorento', 'EV battery depleted - stranded', 'M3 Junction 3, Bagshot', DATEADD(DAY, -14, GETDATE()), 'In Progress'),
('YJ43 FDD', 'BMW 1 Series', 'Fuel leak - smell of petrol', 'McDonalds car park, Manchester', DATEADD(DAY, -14, GETDATE()), 'In Progress'),
('LP62 AQQ', 'Ford Fiesta', 'Exhaust fell off', 'A2 near Canterbury', DATEADD(DAY, -14, GETDATE()), 'Pending'),
('HW50 AFF', 'Audi Q5', 'Battery flat - lights left on', 'A1 near Newark', DATEADD(DAY, -14, GETDATE()), 'Pending'),
('UD19 FKK', 'Nissan Leaf', 'Exhaust fell off', 'A2 near Canterbury', DATEADD(DAY, -14, GETDATE()), 'In Progress'),
('YK49 BGG', 'Vauxhall Mokka', 'Flat tyre', 'M4 Junction 32, Cardiff', DATEADD(DAY, -14, GETDATE()), 'Completed'),
('OD77 SSS', 'Skoda Superb', 'Air bag warning light', 'M62 Junction 8, Warrington', DATEADD(DAY, -14, GETDATE()), 'In Progress'),
('CK14 EGG', 'Citroen Berlingo', 'Engine warning light', 'M1 Junction 15A, Northampton', DATEADD(DAY, -14, GETDATE()), 'In Progress'),
('RD86 DGG', 'Mini Cooper', 'Brake disc cracked', 'A1 near Stevenage', DATEADD(DAY, -15, GETDATE()), 'Completed'),
('UP18 DBB', 'Seat Leon', 'Turbo failure - loss of power', 'M1 Junction 24, East Midlands', DATEADD(DAY, -15, GETDATE()), 'Completed'),
('YU15 GDD', 'Honda Jazz', 'DPF clogged - engine loss', 'M25 Junction 12, Reigate', DATEADD(DAY, -15, GETDATE()), 'Completed'),
('YP28 GKK', 'Vauxhall Insignia', 'Coolant leak', 'A40 near Witney', DATEADD(DAY, -15, GETDATE()), 'Completed'),
('YK96 BKK', 'Mercedes A-Class', 'Cracked windscreen - unsafe', 'A3 near Guildford', DATEADD(DAY, -16, GETDATE()), 'In Progress'),
('AL93 HHH', 'Mazda CX-5', 'ABS warning light on', 'M3 Junction 4, Fleet', DATEADD(DAY, -16, GETDATE()), 'Completed'),
('NV24 ELL', 'Audi TT', 'Traction control fault', 'M6 Toll near Cannock', DATEADD(DAY, -16, GETDATE()), 'Completed'),
('DR64 GKK', 'Toyota RAV4', 'Exhaust fell off', 'A1 near Grantham', DATEADD(DAY, -16, GETDATE()), 'In Progress'),
('XN26 DHH', 'Peugeot 2008', 'Flat tyre', 'Asda car park, Leeds', DATEADD(DAY, -16, GETDATE()), 'Completed'),
('XR16 ELL', 'Volkswagen Passat', 'Gearbox fault', 'A3 near Guildford', DATEADD(DAY, -16, GETDATE()), 'In Progress'),
('BD41 APP', 'Nissan Juke', 'Battery flat - lights left on', 'A1 near Stevenage', DATEADD(DAY, -16, GETDATE()), 'Completed'),
('UW19 AJJ', 'Mazda CX-5', 'Clutch slipping', 'M62 Junction 22, Rishworth', DATEADD(DAY, -17, GETDATE()), 'Completed'),
('HB44 GLL', 'Fiat 500', 'Gearbox oil leak', 'M62 Junction 18, Simister', DATEADD(DAY, -17, GETDATE()), 'In Progress'),
('ET74 UUU', 'Peugeot 208', 'Steering column fault', 'M1 Junction 19, Lutterworth', DATEADD(DAY, -17, GETDATE()), 'Completed'),
('PN64 ALL', 'BMW X3', 'Clutch slipping', 'M3 Junction 4, Fleet', DATEADD(DAY, -17, GETDATE()), 'Completed'),
('YA97 EBB', 'Peugeot 2008', 'Flat tyre', 'A66 near Darlington', DATEADD(DAY, -17, GETDATE()), 'Completed'),
('DJ12 FFF', 'Ford Kuga', 'Electric power steering fault', 'M23 Junction 8, Crawley', DATEADD(DAY, -18, GETDATE()), 'Completed'),
('UA42 AKK', 'Kia Sportage', 'Gearbox oil leak', 'A19 near Sunderland', DATEADD(DAY, -18, GETDATE()), 'Completed'),
('HJ51 UUU', 'BMW 5 Series', 'Coolant leak', 'M4 Junction 37, Bridgend', DATEADD(DAY, -18, GETDATE()), 'Completed'),
('AL93 CCC', 'Mercedes A-Class', 'Gearbox fault', 'High Street, Norwich', DATEADD(DAY, -18, GETDATE()), 'Completed'),
('NH13 GGG', 'Vauxhall Insignia', 'Won''t start', 'M6 Junction 9, Wednesbury', DATEADD(DAY, -19, GETDATE()), 'Completed'),
('JR78 DFF', 'Citroen C5 Aircross', 'Turbo failure - loss of power', 'M3 Junction 3, Bagshot', DATEADD(DAY, -19, GETDATE()), 'Completed'),
('ND16 EHH', 'Nissan Navara', 'Ran out of fuel', 'Sainsbury''s, Exeter', DATEADD(DAY, -19, GETDATE()), 'Completed'),
('KM26 DBB', 'Jaguar XE', 'Power steering loss', 'A46 near Newark', DATEADD(DAY, -19, GETDATE()), 'Completed'),
('CS28 AKK', 'Vauxhall Mokka', 'CV joint clicking - broken', 'Asda car park, Leeds', DATEADD(DAY, -19, GETDATE()), 'Completed'),
('MX22 PPP', 'Fiat 500', 'Alternator failure', 'A66 near Penrith', DATEADD(DAY, -20, GETDATE()), 'Completed'),
('PN84 ATT', 'Renault Clio', 'Alternator failure', 'A34 near Newbury', DATEADD(DAY, -20, GETDATE()), 'Completed'),
('BY92 DDD', 'Ford Focus', 'Gearbox fault', 'A14 Junction 45, Newmarket', DATEADD(DAY, -20, GETDATE()), 'Completed'),
('WS38 GHH', 'Ford Fiesta', 'Jump start needed', 'M1 Junction 28, Mansfield', DATEADD(DAY, -20, GETDATE()), 'Completed'),
('EL19 ACC', 'Volkswagen Polo', 'EV battery depleted - stranded', 'M62 Junction 8, Warrington', DATEADD(DAY, -20, GETDATE()), 'Completed'),
('SW29 DFF', 'BMW X3', 'Clutch slipping', 'A34 near Newbury', DATEADD(DAY, -20, GETDATE()), 'Completed'),
('HV54 BAA', 'Skoda Octavia', 'Alternator belt snapped', 'Town centre, Coventry', DATEADD(DAY, -20, GETDATE()), 'Completed'),
('MC65 EGG', 'Suzuki Swift', 'Immobiliser fault', 'M1 Junction 28, Mansfield', DATEADD(DAY, -20, GETDATE()), 'Completed'),
('LW75 GFF', 'Nissan Navara', 'Gearbox stuck in second', 'M4 Junction 32, Cardiff', DATEADD(DAY, -20, GETDATE()), 'Completed'),
('DJ31 DHH', 'Seat Leon', 'Bonnet latch broken', 'M6 Junction 9, Wednesbury', DATEADD(DAY, -20, GETDATE()), 'Completed'),
('BX30 DBB', 'Ford Fiesta', 'DPF clogged - engine loss', 'A55 near Bangor', DATEADD(DAY, -20, GETDATE()), 'In Progress'),
('OF30 DDD', 'BMW 5 Series', 'Coolant leak', 'High Street, Barnet', DATEADD(DAY, -20, GETDATE()), 'In Progress'),
('NM88 CEE', 'Hyundai Tucson', 'Starter solenoid fault', 'A38 near Lichfield', DATEADD(DAY, -20, GETDATE()), 'Completed'),
('CL44 GDD', 'Audi A4', 'Battery flat - lights left on', 'A14 Junction 45, Newmarket', DATEADD(DAY, -20, GETDATE()), 'Completed'),
('SY28 ANN', 'BMW 1 Series', 'Suspension arm broken', 'High Street, Norwich', DATEADD(DAY, -20, GETDATE()), 'Completed');
 
INSERT INTO dbo.CarRecoveries (NumberPlate, CarModel, Issue, Location, BreakdownTime, Status) VALUES
('SF20 DLL', 'Alfa Romeo Giulia', 'Coolant leak', 'B&Q car park, Reading', DATEADD(DAY, -21, GETDATE()), 'In Progress'),
('AV93 APP', 'Toyota RAV4', 'Turbo failure - loss of power', 'M25 Junction 12, Reigate', DATEADD(DAY, -21, GETDATE()), 'Completed'),
('KH75 FGG', 'Ford Transit', 'Charging port fault', 'M25 Junction 12, Reigate', DATEADD(DAY, -21, GETDATE()), 'Completed'),
('EC11 GGG', 'Audi Q7', 'Suspension damage - pothole', 'Lidl car park, Sheffield', DATEADD(DAY, -21, GETDATE()), 'In Progress'),
('EP72 EAA', 'Vauxhall Corsa', 'Steering column fault', 'Asda car park, Leeds', DATEADD(DAY, -21, GETDATE()), 'Completed'),
('RR11 ATT', 'Toyota Corolla', 'Alternator seized', 'M25 Junction 5, Sevenoaks', DATEADD(DAY, -21, GETDATE()), 'Completed'),
('JL90 DFF', 'Volvo XC60', 'Battery flat - lights left on', 'A2 near Rochester', DATEADD(DAY, -22, GETDATE()), 'Completed'),
('GU98 DGG', 'Ford Transit', 'Flat tyre', 'M20 Junction 8, Maidstone', DATEADD(DAY, -22, GETDATE()), 'Completed'),
('MU37 BAA', 'Suzuki Swift', 'Electric power steering fault', 'A19 near Sunderland', DATEADD(DAY, -22, GETDATE()), 'Completed'),
('KJ74 GEE', 'Citroen Berlingo', 'ABS warning light on', 'M6 Junction 9, Wednesbury', DATEADD(DAY, -22, GETDATE()), 'Completed'),
('TC91 FEE', 'Hyundai Kona', 'Won''t come out of park', 'Asda car park, Leeds', DATEADD(DAY, -23, GETDATE()), 'Completed'),
('KX21 DKK', 'Volvo XC60', 'Gearbox oil leak', 'Town centre, Coventry', DATEADD(DAY, -23, GETDATE()), 'Completed'),
('XG42 EBB', 'Nissan Navara', 'Oil pressure warning', 'Lidl car park, Sheffield', DATEADD(DAY, -23, GETDATE()), 'In Progress'),
('PB18 BFF', 'BMW X5', 'Battery dead', 'A1 near Peterborough', DATEADD(DAY, -23, GETDATE()), 'Completed'),
('RN18 MMM', 'Jeep Renegade', 'Brake disc cracked', 'A316 near Twickenham', DATEADD(DAY, -23, GETDATE()), 'Completed'),
('JF57 JJJ', 'Audi TT', 'Brake disc cracked', 'M62 Junction 22, Rishworth', DATEADD(DAY, -23, GETDATE()), 'Completed'),
('YT90 OOO', 'Mercedes GLC', 'Starter solenoid fault', 'Sainsbury''s, Exeter', DATEADD(DAY, -23, GETDATE()), 'Completed'),
('PF28 AHH', 'Citroen Berlingo', 'Jump start needed', 'A2 near Canterbury', DATEADD(DAY, -24, GETDATE()), 'In Progress'),
('NC79 FAA', 'Ford Puma', 'Hybrid battery warning', 'Lidl car park, Sheffield', DATEADD(DAY, -24, GETDATE()), 'Completed'),
('SJ37 XXX', 'Ford Fiesta', 'Starter solenoid fault', 'M1 Junction 15A, Northampton', DATEADD(DAY, -24, GETDATE()), 'Completed'),
('AU52 SSS', 'Toyota RAV4', 'Brake disc cracked', 'Asda car park, Leeds', DATEADD(DAY, -24, GETDATE()), 'Completed'),
('OU62 EHH', 'Skoda Octavia', 'Flat tyre', 'M3 Junction 4, Fleet', DATEADD(DAY, -24, GETDATE()), 'Completed'),
('HB29 AQQ', 'Seat Tarraco', 'Fuel pump failure', 'M6 Junction 40, Penrith', DATEADD(DAY, -24, GETDATE()), 'Completed'),
('FE64 ELL', 'Seat Ibiza', 'Fuel leak - smell of petrol', 'High Street, Norwich', DATEADD(DAY, -25, GETDATE()), 'Completed'),
('KV33 FLL', 'Citroen C3', 'Coolant leak', 'M40 Junction 1, Hillingdon', DATEADD(DAY, -25, GETDATE()), 'Completed'),
('PN10 FEE', 'Volkswagen Passat', 'Ran out of fuel', 'Asda car park, Leeds', DATEADD(DAY, -25, GETDATE()), 'Completed'),
('KB15 EDD', 'Peugeot 208', 'Starter motor failed', 'A303 near Amesbury', DATEADD(DAY, -25, GETDATE()), 'Completed'),
('UR86 CAA', 'Vauxhall Insignia', 'Traction control fault', 'A38 near Lichfield', DATEADD(DAY, -25, GETDATE()), 'Completed'),
('NV72 DLL', 'Kia Rio', 'Won''t start', 'A34 near Oxford', DATEADD(DAY, -25, GETDATE()), 'Completed'),
('FH34 AKK', 'Audi A4', 'EV battery depleted - stranded', 'M1 Junction 10, Luton', DATEADD(DAY, -25, GETDATE()), 'Completed'),
('BJ27 FLL', 'BMW 1 Series', 'Ran out of fuel', 'M23 Junction 8, Crawley', DATEADD(DAY, -25, GETDATE()), 'Completed'),
('OX91 FHH', 'Citroen Berlingo', 'Wheel bearing noise', 'High Street, Barnet', DATEADD(DAY, -25, GETDATE()), 'Completed'),
('MS13 CGG', 'Seat Tarraco', 'Electric power steering fault', 'M1 Junction 10, Luton', DATEADD(DAY, -25, GETDATE()), 'Completed'),
('NG80 BLL', 'Vauxhall Mokka', 'Cracked windscreen - unsafe', 'A1 near Peterborough', DATEADD(DAY, -25, GETDATE()), 'Completed'),
('WU23 MMM', 'Toyota Prius', 'Key fob not working - locked out', 'M62 Junction 22, Rishworth', DATEADD(DAY, -26, GETDATE()), 'Completed'),
('US15 CFF', 'Renault Kadjar', 'Won''t start', 'Tesco car park, Bristol', DATEADD(DAY, -26, GETDATE()), 'Completed'),
('OA24 DDD', 'Seat Leon', 'Gearbox stuck in second', 'A1 near Peterborough', DATEADD(DAY, -26, GETDATE()), 'Completed'),
('RD65 AKK', 'Kia Sportage', 'Alternator failure', 'M1 Junction 28, Mansfield', DATEADD(DAY, -26, GETDATE()), 'Completed'),
('HE48 BJJ', 'Audi A4', 'Won''t start', 'M4 Junction 47, Swansea', DATEADD(DAY, -27, GETDATE()), 'Completed'),
('DF38 FKK', 'Ford Kuga', 'Oil pressure warning', 'M1 Junction 28, Mansfield', DATEADD(DAY, -27, GETDATE()), 'Completed'),
('YB96 ALL', 'Honda HR-V', 'CV joint clicking - broken', 'M4 Junction 37, Bridgend', DATEADD(DAY, -27, GETDATE()), 'Completed'),
('KN13 CEE', 'Peugeot 2008', 'Starter motor failed', 'M25 Junction 25, Enfield', DATEADD(DAY, -27, GETDATE()), 'Completed'),
('YP95 ABB', 'Mercedes A-Class', 'Traction control fault', 'M6 Toll near Cannock', DATEADD(DAY, -27, GETDATE()), 'In Progress'),
('LV28 AAA', 'Kia Sportage', 'Power steering loss', 'A1(M) Junction 40, Wakefield', DATEADD(DAY, -28, GETDATE()), 'Completed'),
('YA75 VVV', 'BMW 3 Series', 'Charging port fault', 'A46 near Newark', DATEADD(DAY, -28, GETDATE()), 'Completed'),
('DA45 KKK', 'BMW 1 Series', 'Suspension spring snapped', 'Town centre, Coventry', DATEADD(DAY, -28, GETDATE()), 'Completed'),
('OY11 GGG', 'Seat Ateca', 'Immobiliser fault', 'M25 Junction 30, Thurrock', DATEADD(DAY, -28, GETDATE()), 'Completed'),
('NW15 FAA', 'Ford Kuga', 'Ran out of fuel', 'M4 Junction 47, Swansea', DATEADD(DAY, -28, GETDATE()), 'Completed'),
('AE11 DDD', 'Vauxhall Astra', 'Coolant leak', 'A30 near Exeter', DATEADD(DAY, -28, GETDATE()), 'Completed'),
('OY14 EEE', 'Kia Niro', 'Air bag warning light', 'M40 Junction 15, Warwick', DATEADD(DAY, -29, GETDATE()), 'Completed');
 
INSERT INTO dbo.CarRecoveries (NumberPlate, CarModel, Issue, Location, BreakdownTime, Status) VALUES
('SE16 DCC', 'Audi A3', 'Immobiliser fault', 'A14 Junction 45, Newmarket', DATEADD(DAY, -29, GETDATE()), 'Completed'),
('DA15 DBB', 'Volkswagen Polo', 'Engine overheating', 'A1(M) Junction 40, Wakefield', DATEADD(DAY, -29, GETDATE()), 'Completed'),
('PR48 ARR', 'Renault Kadjar', 'Gearbox fault', 'M25 Junction 12, Reigate', DATEADD(DAY, -31, GETDATE()), 'Completed'),
('LK23 GHH', 'BMW 5 Series', 'Water pump failure', 'M3 Junction 4, Fleet', DATEADD(DAY, -31, GETDATE()), 'Completed'),
('WU23 CDD', 'Nissan Navara', 'Ran out of fuel', 'M62 Junction 22, Rishworth', DATEADD(DAY, -32, GETDATE()), 'Completed'),
('JJ68 OOO', 'Peugeot 208', 'Oil leak - major', 'M4 Junction 37, Bridgend', DATEADD(DAY, -32, GETDATE()), 'Completed'),
('DW57 FAA', 'Audi TT', 'Exhaust fell off', 'M6 Junction 12, Cannock', DATEADD(DAY, -32, GETDATE()), 'Completed'),
('PE20 DHH', 'Kia Niro', 'Flat tyre', 'M1 Junction 24, East Midlands', DATEADD(DAY, -32, GETDATE()), 'Completed'),
('VX84 ALL', 'Renault Kadjar', 'Gearbox fault', 'A66 near Penrith', DATEADD(DAY, -33, GETDATE()), 'Completed'),
('DK16 DCC', 'Ford Kuga', 'Key fob not working - locked out', 'A3 near Hindhead', DATEADD(DAY, -33, GETDATE()), 'In Progress'),
('FX75 AGG', 'Renault Clio', 'Suspension spring snapped', 'Lidl car park, Sheffield', DATEADD(DAY, -33, GETDATE()), 'Completed'),
('RA11 BEE', 'Nissan Navara', 'Bonnet latch broken', 'M23 Junction 8, Crawley', DATEADD(DAY, -33, GETDATE()), 'Completed'),
('JN12 FLL', 'Peugeot 2008', 'Cracked windscreen - unsafe', 'M25 Junction 12, Reigate', DATEADD(DAY, -34, GETDATE()), 'Completed'),
('ED91 BJJ', 'Audi TT', 'Gearbox oil leak', 'A46 near Newark', DATEADD(DAY, -34, GETDATE()), 'Completed'),
('XB62 ZZZ', 'Hyundai i30', 'Engine overheating', 'M1 Junction 19, Lutterworth', DATEADD(DAY, -34, GETDATE()), 'In Progress'),
('OU39 WWW', 'Audi Q7', 'Clutch burnt out', 'M6 Toll near Cannock', DATEADD(DAY, -35, GETDATE()), 'Completed'),
('DX73 GJJ', 'Skoda Octavia', 'Turbo failure - loss of power', 'M25 Junction 17, Chorleywood', DATEADD(DAY, -35, GETDATE()), 'Completed'),
('LW70 CLL', 'Ford Fiesta', 'Electric power steering fault', 'McDonalds car park, Manchester', DATEADD(DAY, -36, GETDATE()), 'Completed'),
('LC82 DBB', 'Vauxhall Mokka', 'Steering column fault', 'M20 Junction 8, Maidstone', DATEADD(DAY, -36, GETDATE()), 'Completed'),
('CA73 FEE', 'Skoda Superb', 'Brake disc cracked', 'A14 near Huntingdon', DATEADD(DAY, -36, GETDATE()), 'Completed'),
('AJ95 FAA', 'Toyota Yaris', 'Jump start needed', 'A38 near Lichfield', DATEADD(DAY, -37, GETDATE()), 'In Progress'),
('LB58 GDD', 'Peugeot 3008', 'Key fob not working - locked out', 'A1(M) Junction 40, Wakefield', DATEADD(DAY, -37, GETDATE()), 'In Progress'),
('HR85 DFF', 'Vauxhall Insignia', 'Water pump failure', 'M6 Junction 21A, Warrington', DATEADD(DAY, -38, GETDATE()), 'Completed'),
('NA78 DAA', 'BMW 3 Series', 'Flat tyre', 'A1 near Peterborough', DATEADD(DAY, -38, GETDATE()), 'Completed'),
('EP26 JJJ', 'Renault Megane', 'Flat tyre', 'Lidl car park, Sheffield', DATEADD(DAY, -38, GETDATE()), 'Completed'),
('WB78 GFF', 'Mazda 3', 'Clutch pedal went to floor', 'M4 Junction 7, Slough', DATEADD(DAY, -39, GETDATE()), 'Completed'),
('NA30 GKK', 'Audi Q5', 'Broken down - no power', 'M25 Junction 25, Enfield', DATEADD(DAY, -39, GETDATE()), 'Completed'),
('BX62 GFF', 'BMW 5 Series', 'Suspension spring snapped', 'High Street, Norwich', DATEADD(DAY, -40, GETDATE()), 'Completed'),
('TT55 PPP', 'Honda CR-V', 'Won''t start', 'M25 Junction 5, Sevenoaks', DATEADD(DAY, -40, GETDATE()), 'Completed'),
('AY63 BFF', 'Renault Captur', 'Clutch burnt out', 'M4 Junction 32, Cardiff', DATEADD(DAY, -40, GETDATE()), 'Completed'),
('TD70 ZZZ', 'Citroen C3', 'Ran out of fuel', 'M1 Junction 36, Barnsley', DATEADD(DAY, -40, GETDATE()), 'In Progress'),
('PK10 AQQ', 'Seat Tarraco', 'DPF clogged - engine loss', 'Town centre, Coventry', DATEADD(DAY, -40, GETDATE()), 'Completed'),
('UN64 NNN', 'Toyota RAV4', 'Flat tyre', 'M4 Junction 32, Cardiff', DATEADD(DAY, -41, GETDATE()), 'In Progress'),
('CE12 CGG', 'Volkswagen Golf', 'Cracked windscreen - unsafe', 'M4 Junction 7, Slough', DATEADD(DAY, -41, GETDATE()), 'Completed'),
('XL53 DDD', 'Renault Megane', 'Ran out of fuel', 'A316 near Twickenham', DATEADD(DAY, -41, GETDATE()), 'In Progress'),
('JU95 GDD', 'Toyota Aygo', 'Suspension spring snapped', 'M1 Junction 36, Barnsley', DATEADD(DAY, -42, GETDATE()), 'In Progress'),
('BN91 BHH', 'Kia Niro', 'Puncture - no spare', 'A1 near Newark', DATEADD(DAY, -42, GETDATE()), 'In Progress'),
('PU30 BFF', 'Vauxhall Corsa', 'Starter solenoid fault', 'M25 Junction 25, Enfield', DATEADD(DAY, -43, GETDATE()), 'In Progress'),
('SX64 GBB', 'BMW 1 Series', 'Oil leak - major', 'M6 Junction 40, Penrith', DATEADD(DAY, -43, GETDATE()), 'Completed'),
('TD53 ECC', 'Audi TT', 'DPF clogged - engine loss', 'A38 near Plymouth', DATEADD(DAY, -43, GETDATE()), 'Completed'),
('OK95 FAA', 'Kia Niro', 'Coolant leak', 'M3 Junction 4, Fleet', DATEADD(DAY, -43, GETDATE()), 'Completed'),
('XX21 AMM', 'BMW 3 Series', 'Water pump failure', 'A3 near Guildford', DATEADD(DAY, -44, GETDATE()), 'Completed'),
('TJ57 RRR', 'Jeep Renegade', 'Engine overheating', 'High Street, Barnet', DATEADD(DAY, -44, GETDATE()), 'Completed'),
('JG45 AFF', 'Ford Fiesta', 'Suspension spring snapped', 'Asda car park, Leeds', DATEADD(DAY, -44, GETDATE()), 'Completed'),
('FN81 EDD', 'Audi Q7', 'Engine warning light', 'A38 near Plymouth', DATEADD(DAY, -44, GETDATE()), 'Completed'),
('YO80 CKK', 'Jeep Renegade', 'Two tyres flat', 'Lidl car park, Sheffield', DATEADD(DAY, -45, GETDATE()), 'Completed'),
('WW50 FFF', 'Honda HR-V', 'Clutch pedal went to floor', 'M11 Junction 7, Harlow', DATEADD(DAY, -45, GETDATE()), 'Completed'),
('RY85 GGG', 'Skoda Fabia', 'ABS warning light on', 'A19 near Sunderland', DATEADD(DAY, -45, GETDATE()), 'Completed'),
('XB71 AKK', 'Mercedes E-Class', 'Cracked windscreen - unsafe', 'High Street, Barnet', DATEADD(DAY, -46, GETDATE()), 'Completed'),
('EH72 CJJ', 'Toyota RAV4', 'CV joint clicking - broken', 'M20 Junction 8, Maidstone', DATEADD(DAY, -46, GETDATE()), 'Completed');
 
INSERT INTO dbo.CarRecoveries (NumberPlate, CarModel, Issue, Location, BreakdownTime, Status) VALUES
('AG84 FAA', 'Renault Kadjar', 'Turbo failure - loss of power', 'M40 Junction 15, Warwick', DATEADD(DAY, -46, GETDATE()), 'Completed'),
('PA34 BLL', 'Honda Civic', 'Suspension spring snapped', 'Tesco car park, Bristol', DATEADD(DAY, -47, GETDATE()), 'Completed'),
('EV73 GEE', 'Fiat 500', 'Ran out of fuel', 'M25 Junction 5, Sevenoaks', DATEADD(DAY, -47, GETDATE()), 'Completed'),
('WG38 CEE', 'Toyota Prius', 'Puncture - no spare', 'A2 near Canterbury', DATEADD(DAY, -47, GETDATE()), 'In Progress'),
('XW54 CAA', 'Audi Q5', 'Alternator seized', 'A30 near Exeter', DATEADD(DAY, -47, GETDATE()), 'Completed'),
('WK41 EGG', 'Seat Tarraco', 'Turbo boost pipe split', 'M4 Junction 37, Bridgend', DATEADD(DAY, -47, GETDATE()), 'Completed'),
('TX18 AHH', 'Mazda CX-5', 'CV joint clicking - broken', 'Lidl car park, Sheffield', DATEADD(DAY, -48, GETDATE()), 'Completed'),
('YS16 WWW', 'BMW X3', 'Traction control fault', 'M3 Junction 3, Bagshot', DATEADD(DAY, -48, GETDATE()), 'Completed'),
('KG61 NNN', 'Land Rover Discovery', 'Turbo failure - loss of power', 'M6 Toll near Cannock', DATEADD(DAY, -48, GETDATE()), 'Completed'),
('WR74 DAA', 'Honda Jazz', 'Wheel bearing noise', 'High Street, Barnet', DATEADD(DAY, -48, GETDATE()), 'Completed'),
('MJ81 CJJ', 'Kia Niro', 'Turbo failure - loss of power', 'Tesco Extra, Leicester', DATEADD(DAY, -49, GETDATE()), 'Completed'),
('PG83 AFF', 'Fiat 500', 'ABS warning light on', 'M25 Junction 12, Reigate', DATEADD(DAY, -49, GETDATE()), 'Completed'),
('TR94 DDD', 'Peugeot 208', 'ABS warning light on', 'A38 near Plymouth', DATEADD(DAY, -49, GETDATE()), 'In Progress'),
('XM83 CJJ', 'Nissan Juke', 'Water pump failure', 'A30 near Exeter', DATEADD(DAY, -49, GETDATE()), 'Completed'),
('TO70 BJJ', 'Nissan Juke', 'Fuel pump failure', 'M1 Junction 15A, Northampton', DATEADD(DAY, -50, GETDATE()), 'Completed'),
('SF38 WWW', 'Nissan Leaf', 'Tyre blowout at speed', 'Sainsbury''s, Exeter', DATEADD(DAY, -50, GETDATE()), 'Completed'),
('UH70 ANN', 'Skoda Octavia', 'Power steering loss', 'M6 Junction 9, Wednesbury', DATEADD(DAY, -50, GETDATE()), 'Completed'),
('KJ34 EGG', 'Nissan Navara', 'Water pump failure', 'A2 near Rochester', DATEADD(DAY, -50, GETDATE()), 'Completed'),
('YR30 FKK', 'Skoda Fabia', 'Clutch burnt out', 'A50 near Stoke-on-Trent', DATEADD(DAY, -50, GETDATE()), 'Completed'),
('GM96 CEE', 'BMW 1 Series', 'Suspension damage - pothole', 'B&Q car park, Reading', DATEADD(DAY, -51, GETDATE()), 'In Progress'),
('SS21 DDD', 'Citroen Berlingo', 'Power steering loss', 'Lidl car park, Sheffield', DATEADD(DAY, -51, GETDATE()), 'Completed'),
('ER75 EAA', 'Volkswagen Polo', 'Starter motor failed', 'A1(M) near Doncaster', DATEADD(DAY, -51, GETDATE()), 'In Progress'),
('BO10 ADD', 'Toyota Corolla', 'Water pump failure', 'A2 near Canterbury', DATEADD(DAY, -51, GETDATE()), 'Completed'),
('OW94 CAA', 'Nissan Juke', 'Turbo boost pipe split', 'Asda car park, Leeds', DATEADD(DAY, -52, GETDATE()), 'Completed'),
('CO87 FCC', 'Audi TT', 'Engine overheating', 'A303 near Amesbury', DATEADD(DAY, -52, GETDATE()), 'Completed'),
('FA24 GJJ', 'Nissan Leaf', 'Ran out of fuel', 'A34 near Oxford', DATEADD(DAY, -52, GETDATE()), 'Completed'),
('NH84 AKK', 'Peugeot 208', 'Brake disc cracked', 'B&Q car park, Reading', DATEADD(DAY, -52, GETDATE()), 'Completed'),
('LF22 BLL', 'Audi A3', 'Ran out of fuel', 'M40 Junction 1, Hillingdon', DATEADD(DAY, -52, GETDATE()), 'Completed'),
('JT19 TTT', 'Volvo V40', 'Immobiliser fault', 'M6 Junction 9, Wednesbury', DATEADD(DAY, -53, GETDATE()), 'In Progress'),
('LD66 ANN', 'Mercedes E-Class', 'Alternator belt snapped', 'A1(M) Junction 40, Wakefield', DATEADD(DAY, -53, GETDATE()), 'Completed'),
('SC69 AJJ', 'Ford Puma', 'Won''t start', 'A50 near Stoke-on-Trent', DATEADD(DAY, -54, GETDATE()), 'Completed'),
('ET96 DCC', 'Volvo XC60', 'Clutch pedal went to floor', 'A406 North Circular, London', DATEADD(DAY, -54, GETDATE()), 'Completed'),
('XT45 DDD', 'Alfa Romeo Giulia', 'Immobiliser fault', 'A46 near Newark', DATEADD(DAY, -55, GETDATE()), 'In Progress'),
('YM80 CEE', 'Hyundai Santa Fe', 'ABS warning light on', 'A3 near Hindhead', DATEADD(DAY, -55, GETDATE()), 'Completed'),
('XV49 AKK', 'Volkswagen Tiguan', 'Alternator belt snapped', 'A1 near Peterborough', DATEADD(DAY, -55, GETDATE()), 'Completed'),
('EK32 BAA', 'Honda HR-V', 'CV joint clicking - broken', 'A1(M) near Doncaster', DATEADD(DAY, -55, GETDATE()), 'Completed'),
('DP94 DAA', 'Hyundai Tucson', 'Alternator belt snapped', 'M23 Junction 8, Crawley', DATEADD(DAY, -55, GETDATE()), 'Completed'),
('XA95 FAA', 'Mini Cooper', 'Engine warning light', 'M23 Junction 8, Crawley', DATEADD(DAY, -56, GETDATE()), 'In Progress'),
('PE20 AGG', 'Hyundai i30', 'Engine overheating', 'M1 Junction 24, East Midlands', DATEADD(DAY, -56, GETDATE()), 'Completed'),
('WS15 DFF', 'Seat Tarraco', 'ABS warning light on', 'A66 near Darlington', DATEADD(DAY, -56, GETDATE()), 'Completed'),
('BW35 GBB', 'Mazda 3', 'Suspension damage - pothole', 'M62 Junction 18, Simister', DATEADD(DAY, -56, GETDATE()), 'Completed'),
('JA24 FLL', 'Volkswagen Passat', 'Alternator seized', 'M40 Junction 1, Hillingdon', DATEADD(DAY, -57, GETDATE()), 'Completed'),
('YV94 DDD', 'Audi Q5', 'Broken down - no power', 'M25 Junction 17, Chorleywood', DATEADD(DAY, -57, GETDATE()), 'Completed'),
('VF51 EEE', 'Mercedes C-Class', 'Oil pressure warning', 'M25 Junction 12, Reigate', DATEADD(DAY, -58, GETDATE()), 'Completed'),
('HS98 EKK', 'Honda Jazz', 'Won''t start', 'M3 Junction 4, Fleet', DATEADD(DAY, -58, GETDATE()), 'In Progress'),
('BR10 EDD', 'Suzuki Swift', 'Suspension damage - pothole', 'M62 Junction 8, Warrington', DATEADD(DAY, -58, GETDATE()), 'Completed'),
('EY21 CBB', 'Nissan Leaf', 'Gearbox oil leak', 'M1 Junction 24, East Midlands', DATEADD(DAY, -58, GETDATE()), 'Completed'),
('PR72 GKK', 'Seat Leon', 'Brake pads worn through', 'A1 near Newark', DATEADD(DAY, -58, GETDATE()), 'Completed'),
('LW34 DFF', 'Vauxhall Mokka', 'Gearbox stuck in second', 'M25 Junction 30, Thurrock', DATEADD(DAY, -59, GETDATE()), 'Completed'),
('SB42 EKK', 'Volkswagen Polo', 'Oil pressure warning', 'A3 near Hindhead', DATEADD(DAY, -59, GETDATE()), 'Completed');
 
INSERT INTO dbo.CarRecoveries (NumberPlate, CarModel, Issue, Location, BreakdownTime, Status) VALUES
('OO30 FFF', 'Mazda CX-5', 'Cracked windscreen - unsafe', 'M40 Junction 15, Warwick', DATEADD(DAY, -59, GETDATE()), 'Completed'),
('FP95 GLL', 'Honda Civic', 'Coolant leak', 'M1 Junction 36, Barnsley', DATEADD(DAY, -60, GETDATE()), 'Completed'),
('EE39 ALL', 'Jeep Renegade', 'Gearbox fault', 'M3 Junction 3, Bagshot', DATEADD(DAY, -60, GETDATE()), 'Completed');

GO
